server:
  port: 8888

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: r1
          uri: http://localhost:8088
          predicates:
            - Path=/clients/**
        - id: r2
          uri: http://localhost:8089
          predicates:
            - Path=/voitures/**
